import type { Metadata } from "next";
import { LegalShell, LegalSection } from "@/components/marketing/legal";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of Floqex.",
};

export default function TermsPage() {
  return (
    <LegalShell
      title="Terms of Service"
      updated="June 22, 2026"
      intro="These Terms of Service ('Terms') govern your access to and use of Floqex. By registering an account or using our services, you agree to be bound by these Terms. If you do not agree to these Terms, do not use the Services. Trading carries significant risk of loss; please review our Risk Disclosures carefully."
    >
      <LegalSection heading="1. Acceptance and Eligibility">
        <p>
          By using Floqex, you represent that you are at least 18 years of age and possess the legal authority to enter into these Terms. You may not use the Services if you are a resident of a jurisdiction where the use of automated trading software is prohibited by law, or if you are subject to applicable economic sanctions.
        </p>
      </LegalSection>

      <LegalSection heading="2. Description of Services & Regulatory Disclaimer">
        <p>
          Floqex is a technology provider offering software that allows users to automate trading strategies on their connected third-party brokerage accounts. <strong>Floqex is not a broker-dealer, registered investment adviser, or fiduciary.</strong> We do not execute trades directly, hold custody of your assets, or provide personalized financial, legal, or tax advice. 
        </p>
        <p className="mt-2 text-fg-muted font-medium bg-warning/10 p-3 rounded-lg border border-warning/20">
          <strong>Important:</strong> Floqex provides routing and automation technology. The strategies, risk parameters, and ultimate execution decisions remain entirely in your control. The platform translates your configurations into API signals. You are solely responsible for all trades executed by your connected broker based on signals generated by the Floqex software.
        </p>
        <p className="mt-2">
          Your use of the Services is at your own risk. The platform provides tools to transmit your strategy logic to your broker; you are solely responsible for configuring, backtesting, and continually monitoring your automated bots during live market hours.
        </p>
      </LegalSection>

      <LegalSection heading="3. Third-Party Broker Integrations">
        <p>
          To use live trading features, you must connect a supported third-party brokerage account via API keys. Floqex is not responsible for the performance, reliability, or execution quality of your connected broker. We disclaim all liability for:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-2">
          <li>Broker API downtime, rate limits, or connection failures.</li>
          <li>Slippage, partial fills, or rejected orders.</li>
          <li>Latency between Floqex sending a signal and the broker executing the trade.</li>
        </ul>
        <p className="mt-2">
          Your relationship with your broker is governed by their separate Terms of Service. Floqex is not a party to that agreement.
        </p>
      </LegalSection>

      <LegalSection heading="4. Third-Party Webhooks & Automation">
        <p>
          You may choose to connect your Floqex account to third-party automation tools (such as Make.com or Zapier) via custom webhooks. By configuring a webhook URL, you authorize Floqex to securely transmit your account data, onboarding survey responses, and trading alerts to the specified endpoint. We are not responsible for the data security, privacy practices, or reliability of any third-party service you choose to integrate with.
        </p>
      </LegalSection>

      <LegalSection heading="5. Subscriptions and Billing">
        <p>
          Floqex is offered on a subscription basis. By selecting a paid plan, you agree to pay the fees specified at checkout.
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-2">
          <li><strong>Auto-Renewal:</strong> Subscriptions automatically renew at the end of each billing cycle unless you cancel beforehand via your account settings.</li>
          <li><strong>Refunds:</strong> All payments are non-refundable, except where required by applicable law. If you cancel mid-cycle, you will retain access to the paid features until the cycle ends.</li>
          <li><strong>Changes to Fees:</strong> We reserve the right to change our pricing with 30 days&apos; advance notice. Continued use of the Services after the price change constitutes your agreement to pay the modified amount.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="5. Prohibited Conduct">
        <p>You agree not to engage in any of the following prohibited activities:</p>
        <ul className="list-disc pl-6 space-y-2 mt-2">
          <li>Reverse engineering, decompiling, or attempting to discover the source code of Floqex.</li>
          <li>Using the platform to engage in market manipulation, spoofing, wash trading, or any illegal financial activity.</li>
          <li>Sharing, selling, or leasing your Floqex account credentials or API keys.</li>
          <li>Overloading our infrastructure or bypassing rate limits through automated scraping or malicious payloads.</li>
        </ul>
        <p className="mt-2">
          We reserve the right to suspend or terminate your account immediately, without notice or refund, if we determine you have violated these terms.
        </p>
      </LegalSection>

      <LegalSection heading="6. Intellectual Property">
        <p>
          Floqex retains all right, title, and interest in and to the Services, including all software, design, text, graphics, and trade secrets. We grant you a limited, non-exclusive, non-transferable, and revocable license to access and use the platform for its intended purposes. You retain ownership of the specific trading strategies and parameters you create within your account.
        </p>
      </LegalSection>

      <LegalSection heading="7. Disclaimers of Warranties">
        <p>
          THE SERVICES ARE PROVIDED ON AN &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; BASIS. FLOQEX EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR COMPLETELY SECURE, NOR DO WE GUARANTEE ANY SPECIFIC TRADING RESULTS OR PROFITABILITY.
        </p>
      </LegalSection>

      <LegalSection heading="8. Limitation of Liability">
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL FLOQEX, ITS DIRECTORS, EMPLOYEES, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO TRADING LOSSES, LOST PROFITS, OR LOSS OF DATA, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE SERVICES.
        </p>
        <p className="mt-2">
          IN NO EVENT SHALL FLOQEX&apos;S TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE GREATER OF ONE HUNDRED U.S. DOLLARS ($100.00) OR THE AMOUNT YOU PAID TO FLOQEX IN THE THREE (3) MONTHS PRECEDING THE CLAIM.
        </p>
      </LegalSection>

      <LegalSection heading="9. Indemnification">
        <p>
          You agree to indemnify, defend, and hold harmless Floqex from and against any and all claims, liabilities, damages, losses, and expenses (including reasonable attorneys&apos; fees) arising out of your use of the Services, your violation of these Terms, or your violation of any laws or rights of a third party.
        </p>
      </LegalSection>

      <LegalSection heading="10. Dispute Resolution and Arbitration">
        <p>
          <strong>Please read this section carefully as it affects your legal rights.</strong> Any dispute arising out of or relating to these Terms or the Services shall be resolved through binding arbitration administered by the American Arbitration Association (AAA) in accordance with its Commercial Arbitration Rules. The arbitration shall take place in Delaware, USA.
        </p>
        <p className="mt-2">
          <strong>Class Action Waiver:</strong> You and Floqex agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action.
        </p>
      </LegalSection>

      <LegalSection heading="11. Governing Law">
        <p>
          These Terms and any dispute related to them shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law principles.
        </p>
      </LegalSection>

      <LegalSection heading="12. Changes to Terms">
        <p>
          We may modify these Terms at any time. If we make material changes, we will provide notice through the platform or via email. Your continued use of the Services after the effective date of the revised Terms constitutes your acceptance of the changes. If you have questions, please contact <a href="mailto:hello@floqex.com" className="text-accent hover:underline">hello@floqex.com</a>.
        </p>
      </LegalSection>
    </LegalShell>
  );
}
